let DATA={profiles:[],courses:{}},state={profile:null,course:null,lesson:null,card:0,score:0};
const $=s=>document.querySelector(s),app=document.querySelector('#app');
const store={get(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
const prog=()=>store.get('md-progress-v4',store.get('md-progress',{}));
const LEARNING_KEY='md-learning-v1',REVIEW_INTERVALS=[1,3,7,14,30],XP_REWARDS={lesson:15,review:10,dailyGoal:20};
const learning=()=>store.get(LEARNING_KEY,{profiles:{}});
function profileLearning(){const root=learning();return root.profiles[state.profile]||{xp:0,currentStreak:0,bestStreak:0,lastActivityDate:null,lessons:{},activity:[]}}
function saveProfileLearning(data){const root=learning();root.profiles[state.profile]=data;store.set(LEARNING_KEY,root)}
function lessonLearning(cid,lid){return profileLearning().lessons[key(cid,lid)]||null}
function addDays(iso,days){const d=new Date(iso);d.setDate(d.getDate()+days);return d.toISOString()}
function registerActivity(type,cid,lid){const data=profileLearning(),today=localDay(),last=data.lastActivityDate;
  if(last!==today){const yesterday=localDay(new Date(Date.now()-86400000));data.currentStreak=last===yesterday?(data.currentStreak||0)+1:1;data.bestStreak=Math.max(data.bestStreak||0,data.currentStreak);data.lastActivityDate=today}
  const xp=XP_REWARDS[type]||0;data.xp=(data.xp||0)+xp;data.activity=[...(data.activity||[]),{type,cid,lid,date:new Date().toISOString(),xp}].slice(-500);saveProfileLearning(data);return xp}
function migrateLearning(){const data=profileLearning();let changed=false;for(const [k,v] of Object.entries(prog())){if(!k.startsWith(state.profile+':')||!v?.date||data.lessons[k])continue;data.lessons[k]={completed:true,completedAt:v.date,lastOpened:v.date,reviewCount:0,lastReview:null,nextReview:addDays(v.date,1)};changed=true}if(changed)saveProfileLearning(data)}
function markOpened(cid,lid){const data=profileLearning(),k=key(cid,lid),r=data.lessons[k]||{};r.lastOpened=new Date().toISOString();data.lessons[k]=r;saveProfileLearning(data)}
function completeLessonActivity(cid,lid){const data=profileLearning(),k=key(cid,lid),now=new Date().toISOString(),r=data.lessons[k]||{},first=!r.completed;r.completed=true;r.completedAt=r.completedAt||now;r.lastOpened=now;r.nextReview=r.nextReview||addDays(now,1);r.reviewCount=r.reviewCount||0;data.lessons[k]=r;saveProfileLearning(data);return first?registerActivity('lesson',cid,lid):0}
function markReviewed(cid,lid){const data=profileLearning(),k=key(cid,lid),now=new Date().toISOString(),r=data.lessons[k]||{completed:true,completedAt:now};r.reviewCount=(r.reviewCount||0)+1;r.lastReview=now;r.lastOpened=now;const interval=REVIEW_INTERVALS[Math.min(r.reviewCount,REVIEW_INTERVALS.length-1)];r.nextReview=addDays(now,interval);data.lessons[k]=r;saveProfileLearning(data);registerActivity('review',cid,lid)}
function dueReviews(){migrateLearning();const now=Date.now(),data=profileLearning();return Object.entries(data.lessons).filter(([,r])=>r.completed&&r.nextReview&&new Date(r.nextReview).getTime()<=now).map(([k,r])=>{const [,cid,lid]=k.split(':');const lesson=C(cid)?.lessons.find(x=>x.id===lid);return lesson?{cid,lid,lesson,record:r}:null}).filter(Boolean).sort((a,b)=>new Date(a.record.nextReview)-new Date(b.record.nextReview))}
function learningStats(){migrateLearning();const d=profileLearning();return{xp:d.xp||0,streak:d.currentStreak||0,best:d.bestStreak||0,reviews:(d.activity||[]).filter(a=>a.type==='review').length,due:dueReviews().length}}
const sett=()=>store.get('md-settings',{theme:'light',font:17,contrast:false});
function apply(){const s=sett();document.documentElement.dataset.theme=s.theme;document.documentElement.dataset.contrast=s.contrast?'high':'normal';document.documentElement.style.setProperty('--fs',s.font+'px')}
function P(){return DATA.profiles.find(x=>x.id===state.profile)}
function C(id=state.course){return DATA.courses[id]}
function key(cid,lid){return`${state.profile}:${cid}:${lid}`}
function done(cid,lid){return!!prog()[key(cid,lid)]}
function allWords(){return P().courses.flatMap(cid=>(C(cid)?.lessons||[]).flatMap(l=>l.words.map(w=>({...w,cid,lid:l.id}))))}
function stats(){let total=0,lessons=0,finished=0;P().courses.forEach(cid=>(C(cid)?.lessons||[]).forEach(l=>{lessons++;total+=l.words.length;if(done(cid,l.id))finished++}));return{total,lessons,finished}}

function localDay(d=new Date()){const x=new Date(d);return`${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`}
function progressEntries(){return Object.entries(prog()).filter(([k,v])=>k.startsWith(state.profile+':')&&v?.date)}
function activitySummary(){
  migrateLearning();const ld=profileLearning();
  const days=[...new Set(progressEntries().map(([,v])=>localDay(v.date)))].sort();
  const today=localDay(),yesterday=localDay(new Date(Date.now()-86400000));
  let streak=0,cursor=days.includes(today)?new Date():days.includes(yesterday)?new Date(Date.now()-86400000):null;
  while(cursor&&days.includes(localDay(cursor))){streak++;cursor=new Date(cursor.getTime()-86400000)}
  const last=days.length?days.at(-1):null;
  return{streak:ld.currentStreak||streak,last:ld.lastActivityDate||last,todayDone:progressEntries().filter(([,v])=>localDay(v.date)===today).length}
}
function formatActivityDate(day){if(!day)return'ще немає';if(day===localDay())return'сьогодні';if(day===localDay(new Date(Date.now()-86400000)))return'учора';return new Date(day+'T12:00:00').toLocaleDateString('uk-UA',{day:'numeric',month:'short'})}
const DAILY_PLANS={
  inna:[
    {icon:'🩺',title:'Медична німецька',detail:'Пройти наступний короткий урок',course:'inna-radiology'},
    {icon:'🚗',title:'Führerschein',detail:'Вивчити дорожні слова й ситуації',course:'roma-driving'},
    {icon:'🎓',title:'Підготовка до B2',detail:'Формальне спілкування та письмо',course:'inna-formal'}
  ],
  roma:[
    {icon:'💼',title:'Робота й Ausbildung',detail:'Пройти наступний кар’єрний урок',course:'roma-career'},
    {icon:'🚗',title:'Führerschein',detail:'Повторити дорожню лексику',course:'roma-driving'},
    {icon:'🇩🇪',title:'Життя в Німеччині',detail:'Практична ситуація на щодень',course:'roma-life'}
  ],
  nazar:[
    {icon:'📚',title:'Німецька для 7 класу',detail:'Наступний шкільний мікроурок',course:'nazar-school'},
    {icon:'✍️',title:'Schreiben',detail:'Слова й фрази для письмової роботи',course:'nazar-writing'},
    {icon:'🏫',title:'Шкільна ситуація',detail:'Практична мова після школи',course:'nazar-situations-plus'}
  ]
};
function nextLesson(cid){const c=C(cid);return c?.lessons.find(l=>!done(cid,l.id))||c?.lessons[0]}
function dailyPlan(){return(DAILY_PLANS[state.profile]||[]).map((t,i)=>{const l=nextLesson(t.course);return{...t,index:i,lesson:l,complete:l?done(t.course,l.id):false}})}
function openDailyTask(i){const t=dailyPlan()[i];if(!t?.lesson)return;state.course=t.course;start(t.lesson.id)}
function todayHtml(){const a=activitySummary(),ls=learningStats(),tasks=dailyPlan(),complete=tasks.filter(t=>t.complete).length,minutes=tasks.reduce((n,t)=>n+(Number(t.lesson?.duration)||5),0);return`<section class="today-card"><div class="today-top"><div><div class="tagline">${state.profile==='nazar'?'📚 Після школи':'🎯 План на сьогодні'}</div><h2>${complete===tasks.length?'План виконано — чудова робота!':'Три маленькі кроки вперед'}</h2></div><div class="today-time">≈ ${minutes} хв</div></div><div class="today-progress"><i style="width:${Math.round(complete/tasks.length*100)||0}%"></i></div>${ls.due?`<button class="repeat-today" onclick="review()"><span>🧠</span><span><b>Повторити сьогодні</b><small>${ls.due} ${ls.due===1?'урок готовий':'уроків готові'} до повторення</small></span><strong>›</strong></button>`:''}<div class="today-tasks">${tasks.map(t=>`<button class="today-task ${t.complete?'complete':''}" onclick="openDailyTask(${t.index})"><span class="task-icon">${t.complete?'✓':t.icon}</span><span><b>${t.title}</b><small>${t.complete?'Виконано сьогодні':t.detail}</small></span><span class="task-arrow">›</span></button>`).join('')}</div><div class="today-meta"><span>🔥 Серія: <b>${a.streak} ${a.streak===1?'день':'днів'}</b></span><span>⭐ XP: <b>${ls.xp}</b></span><span>🧠 До повторення: <b>${ls.due}</b></span></div></section>`}

function speak(t){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='de-DE';u.rate=.82;speechSynthesis.speak(u)}
function nav(a){return`<nav class="bottom">${[['home','⌂','Головна'],['courses','▤','Курси'],['review','◫','Повторення'],['progress','◔','Прогрес']].map(x=>`<button class="navbtn ${a===x[0]?'active':''}" onclick="go('${x[0]}')"><b>${x[1]}</b>${x[2]}</button>`).join('')}</nav>`}
function shell(html,a='home'){app.innerHTML=`<main class="app"><header class="top"><div class="brand">Mein <span>Deutsch</span></div><button class="iconbtn" onclick="settings()">⚙︎</button></header>${html}</main>${state.profile?nav(a):''}`}
function profiles(){state.profile=null;shell(`<section class="hero"><div class="tagline">Lernen. Verstehen. Sprechen.</div><h1>Mein Deutsch</h1><p>Модульний сімейний курс німецької. Нові теми можна підключати без втрати прогресу.</p></section><div class="sectionhead"><h2>Хто навчається?</h2><span class="small">Версія ${DATA.version}</span></div><div class="grid">${DATA.profiles.map(p=>`<button class="card profile" onclick="choose('${p.id}')"><div class="emoji">${p.emoji}</div><h2>${p.name}</h2><div class="sub">${p.subtitle}</div></button>`).join('')}</div>`)}
function choose(id){state.profile=id;store.set('md-last',id);home()}
function home(){const s=stats();shell(`<section class="hero compact-hero"><div class="tagline">Willkommen zurück</div><h1>Привіт, ${P().greetingName}! ${P().emoji}</h1><p>${state.profile==='nazar'?'Після школи достатньо кількох коротких завдань.':'Сьогодні достатньо кількох коротких кроків, щоб рухатися вперед.'}</p></section>${todayHtml()}<div class="stats"><div class="stat"><b>${s.total.toLocaleString('uk-UA')}</b>слів і фраз</div><div class="stat"><b>${s.lessons}</b>мікроуроків</div><div class="stat"><b>${s.finished}</b>завершено</div></div><div class="sectionhead"><h2>Твій навчальний шлях</h2><button class="btn ghost" onclick="profiles()">Змінити профіль</button></div>${courseGroupsHtml()}`,'home')}
function courseGroupsHtml(){const groups=P().courseGroups||[{title:'Курси',courses:P().courses}];return groups.map(g=>`<section class="course-group"><div class="sectionhead"><h2>${g.title}</h2></div><div class="grid">${g.courses.map(courseCard).join('')}</div></section>`).join('')}
function courseCard(cid){const c=C(cid);if(!c)return'';const d=c.lessons.filter(l=>done(cid,l.id)).length,pc=Math.round(d/c.lessons.length*100)||0,n=c.lessons.reduce((a,l)=>a+l.words.length,0);return`<article class="card course" onclick="openCourse('${cid}')"><div class="emoji">${c.icon}</div><h3>${c.title}</h3><div class="sub">${c.description}</div><p class="metric">${c.lessons.length} уроків · ${n.toLocaleString('uk-UA')} карток</p><div class="progress"><i style="width:${pc}%"></i></div></article>`}
function openCourse(cid){state.course=cid;courses()}
function courses(){if(!state.course)state.course=P().courses[0];const c=C();shell(`<div class="sectionhead"><div><button class="btn ghost" onclick="home()">← Назад</button><h2>${c.icon} ${c.title}</h2></div><span class="small">${c.lessons.length} уроків</span></div><div class="lesson-list">${c.lessons.map((l,i)=>`<article class="lesson ${done(state.course,l.id)?'done':''}"><div class="bubble">${done(state.course,l.id)?'✓':i+1}</div><div><h3>${l.title}</h3><small>${l.words.length} карток · ${l.duration} хв</small></div><button class="btn" onclick="start('${l.id}')">${done(state.course,l.id)?'Повторити':'Почати'}</button></article>`).join('')}</div>`,'courses')}
function start(lid){state.lesson=C().lessons.find(l=>l.id===lid);markOpened(state.course,lid);state.card=0;state.score=0;study()}
function study(){const l=state.lesson,w=l.words[state.card];shell(`<div class="sectionhead"><button class="btn ghost" onclick="courses()">← Уроки</button><span>${state.card+1}/${l.words.length}</span></div><section class="card study"><div class="small">${l.title} · ${w.level||''}</div><div class="word">${w.de}</div><div class="translation">${w.uk}</div>${w.exampleDe?`<div class="example"><b>${w.exampleDe}</b><br>${w.exampleUk||''}</div>`:''}<div class="actions"><button class="btn secondary" onclick='speak(${JSON.stringify(w.de)})'>🔊 Прослухати</button><button class="btn" onclick="nextStudy()">${state.card===l.words.length-1?'До тесту':'Далі →'}</button></div></section>`,'courses')}
function nextStudy(){if(state.card<state.lesson.words.length-1){state.card++;study()}else{state.card=0;quiz()}}
function shuffle(a){return[...a].sort(()=>Math.random()-.5)}
function quiz(){const l=state.lesson,w=l.words[state.card],pool=allWords().filter(x=>x.uk!==w.uk&&x.de!==w.de),opts=shuffle([w,...shuffle(pool).slice(0,3)]);shell(`<div class="sectionhead"><button class="btn ghost" onclick="courses()">← Вийти</button><span>Тест ${state.card+1}/${l.words.length}</span></div><section class="card study"><div class="small">Обери правильний переклад</div><div class="word" style="font-size:clamp(1.5rem,7vw,3rem)">${w.de}</div><div class="quiz-options">${opts.map(o=>`<button class="option" onclick='answer(this,${JSON.stringify(o.uk)},${JSON.stringify(w.uk)})'>${o.uk}</button>`).join('')}</div><div id="feedback"></div></section>`,'courses')}
function answer(btn,val,right){document.querySelectorAll('.option').forEach(x=>x.disabled=true);const ok=val===right;if(ok)state.score++;btn.classList.add(ok?'good':'bad');if(!ok)[...document.querySelectorAll('.option')].find(x=>x.textContent===right)?.classList.add('good');$('#feedback').innerHTML=`<p><b>${ok?'Правильно! ✓':'Правильна відповідь: '+right}</b></p><button class="btn" onclick="nextQuiz()">Далі</button>`}
function nextQuiz(){if(state.card<state.lesson.words.length-1){state.card++;quiz()}else{const p=prog(),wasDone=done(state.course,state.lesson.id);p[key(state.course,state.lesson.id)]={date:new Date().toISOString(),score:state.score,total:state.lesson.words.length};store.set('md-progress-v4',p);const earned=completeLessonActivity(state.course,state.lesson.id);shell(`<section class="hero"><div class="tagline">Sehr gut!</div><h1>${wasDone?'Повторення завершено':'Урок завершено'}</h1><p>Правильних відповідей: ${state.score} із ${state.lesson.words.length}.${earned?` Отримано +${earned} XP.`:''}</p></section><div class="card"><button class="btn" onclick="courses()">Повернутися до курсу</button></div>`,'courses')}}
function review(){const due=dueReviews(),ls=learningStats();shell(`<section class="hero compact-hero"><div class="tagline">Smart Repetition</div><h1>Повторення</h1><p>Інтервали автоматично зростають: 1 → 3 → 7 → 14 → 30 днів.</p></section><div class="review-summary"><div class="stat"><b>${due.length}</b>сьогодні</div><div class="stat"><b>${ls.reviews}</b>виконано</div><div class="stat"><b>${ls.xp}</b>XP</div></div>${due.length?`<div class="sectionhead"><h2>Повторити сьогодні</h2></div><div class="review-queue">${due.map((x,i)=>`<article class="lesson review-item"><div class="bubble">🧠</div><div><h3>${x.lesson.title}</h3><small>${C(x.cid).title} · повторень: ${x.record.reviewCount||0}</small></div><button class="btn" onclick="reviewDone('${x.cid}','${x.lid}')">Повторено ✓</button></article>`).join('')}</div>`:`<section class="card empty-review"><div class="emoji">✨</div><h2>На сьогодні все!</h2><p class="sub">Наступні уроки з’являться тут автоматично у потрібний день.</p></section>`}<div class="sectionhead"><h2>Вільне повторення</h2><span class="small">20 випадкових карток</span></div><input class="search" placeholder="Пошук німецькою або українською" oninput="filterCards(this.value)"><div class="review-grid" id="reviewCards" style="margin-top:12px">${shuffle(allWords()).slice(0,20).map(cardHtml).join('')}</div>`,'review')}
function reviewDone(cid,lid){markReviewed(cid,lid);review()}
function cardHtml(w){return`<article class="card vocab"><h3>${w.de}</h3><p class="sub">${w.uk}</p>${w.exampleDe?`<p class="small">${w.exampleDe}</p>`:''}<button class="btn secondary" onclick='speak(${JSON.stringify(w.de)})'>🔊</button></article>`}
function filterCards(q){q=q.toLowerCase();const words=q?allWords().filter(w=>(w.de+' '+w.uk+' '+(w.exampleDe||'')).toLowerCase().includes(q)).slice(0,80):shuffle(allWords()).slice(0,20);$('#reviewCards').innerHTML=words.map(cardHtml).join('')}
function progressView(){const s=stats(),ls=learningStats(),pc=Math.round(s.finished/s.lessons*100)||0;shell(`<section class="hero"><div class="tagline">Dein Fortschritt</div><h1>${pc}% шляху</h1><p>${s.finished} із ${s.lessons} уроків завершено.</p></section><div class="stats"><div class="stat"><b>${ls.xp}</b>XP</div><div class="stat"><b>${ls.streak}</b>поточна серія</div><div class="stat"><b>${ls.best}</b>найкраща серія</div></div><div class="card" style="margin-top:12px"><div class="progress" style="height:16px"><i style="width:${pc}%"></i></div></div><div class="sectionhead"><h2>За курсами</h2></div>${courseGroupsHtml()}`,'progress')}
function go(v){if(v==='home')home();if(v==='courses'){state.course=null;courses()}if(v==='review')review();if(v==='progress')progressView()}
function exportBackup(){const payload={format:'mein-deutsch-backup',version:DATA.version,createdAt:new Date().toISOString(),progress:prog(),settings:sett(),lastProfile:store.get('md-last',null),favorites:store.get('md-favorites',[]),learning:learning()};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='mein-deutsch-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function importBackup(){const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=async()=>{try{const data=JSON.parse(await input.files[0].text());if(data.format!=='mein-deutsch-backup')throw Error('format');if(data.progress)store.set('md-progress-v4',data.progress);if(data.settings)store.set('md-settings',data.settings);if(data.lastProfile)store.set('md-last',data.lastProfile);if(data.favorites)store.set('md-favorites',data.favorites);if(data.learning)store.set(LEARNING_KEY,data.learning);apply();alert('Резервну копію відновлено.');location.reload()}catch(e){alert('Не вдалося прочитати резервну копію.')}};input.click()}
function resetProgress(){if(confirm('Справді видалити весь навчальний прогрес?')){localStorage.removeItem('md-progress-v4');localStorage.removeItem(LEARNING_KEY);location.reload()}}
function settings(){const s=sett();document.body.insertAdjacentHTML('beforeend',`<div class="modal" onclick="if(event.target===this)this.remove()"><div class="sheet"><h2>Комфорт для очей</h2><div class="setting"><span>Темна тема</span><button class="btn secondary" onclick="theme()">${s.theme==='dark'?'Увімкнено':'Вимкнено'}</button></div><div class="setting"><span>Високий контраст</span><button class="btn secondary" onclick="contrast()">${s.contrast?'Увімкнено':'Вимкнено'}</button></div><div class="setting"><span>Розмір тексту</span><div><button class="iconbtn" onclick="font(-1)">A−</button> <button class="iconbtn" onclick="font(1)">A+</button></div></div><div class="setting"><span>Резервна копія</span><div><button class="btn secondary" onclick="exportBackup()">Експорт</button> <button class="btn secondary" onclick="importBackup()">Імпорт</button></div></div><div class="setting"><span>Скинути прогрес</span><button class="btn secondary" onclick="resetProgress()">Скинути</button></div><button class="btn" onclick="this.closest('.modal').remove()">Готово</button></div></div>`)}
function theme(){const s=sett();s.theme=s.theme==='dark'?'light':'dark';store.set('md-settings',s);apply();document.querySelector('.modal').remove();settings()}
function contrast(){const s=sett();s.contrast=!s.contrast;store.set('md-settings',s);apply();document.querySelector('.modal').remove();settings()}
function font(d){const s=sett();s.font=Math.max(15,Math.min(23,s.font+d));store.set('md-settings',s);apply()}
async function loadData(){const catalog=await fetch('content/catalog.json',{cache:'no-cache'}).then(r=>{if(!r.ok)throw Error('catalog');return r.json()});const packages=await Promise.all(catalog.packages.map(async p=>{const x=await fetch(p.path,{cache:'no-cache'}).then(r=>{if(!r.ok)throw Error(p.path);return r.json()});return x}));DATA={version:catalog.contentVersion,profiles:catalog.profiles,courses:Object.fromEntries(packages.map(x=>[x.packageId,x.course]))};return DATA}
loadData().then(()=>{apply();const last=store.get('md-last',null);if(last&&DATA.profiles.some(p=>p.id===last)){state.profile=last;home()}else profiles()}).catch(e=>{console.error(e);app.innerHTML='<div class="loading">Не вдалося завантажити модулі. Оновіть сторінку.</div>'});
if('serviceWorker' in navigator){navigator.serviceWorker.register('sw.js?v=2.3.0').then(reg=>reg.update()).catch(console.error);navigator.serviceWorker.addEventListener('controllerchange',()=>{if(!sessionStorage.getItem('md-reloaded-2.3.0')){sessionStorage.setItem('md-reloaded-2.3.0','1');location.reload()}})}
